USE [master]
GO

/****** Object:  Database [ControleDespesas]    Script Date: 23/05/2020 19:04:44 ******/
CREATE DATABASE [ControleDespesas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ControleDespesas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ControleDespesas.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ControleDespesas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ControleDespesas_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ControleDespesas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ControleDespesas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ControleDespesas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ControleDespesas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ControleDespesas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ControleDespesas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ControleDespesas] SET ARITHABORT OFF 
GO

ALTER DATABASE [ControleDespesas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ControleDespesas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ControleDespesas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ControleDespesas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ControleDespesas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ControleDespesas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ControleDespesas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ControleDespesas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ControleDespesas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ControleDespesas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ControleDespesas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ControleDespesas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ControleDespesas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ControleDespesas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ControleDespesas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ControleDespesas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ControleDespesas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ControleDespesas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ControleDespesas] SET  MULTI_USER 
GO

ALTER DATABASE [ControleDespesas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ControleDespesas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ControleDespesas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ControleDespesas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ControleDespesas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ControleDespesas] SET  READ_WRITE 
GO