USE [ControleDespesas] 

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='Empresa') 
BEGIN
    CREATE TABLE [dbo].[Empresa] (
        [Id] [bigint] IDENTITY(1,1) NOT NULL,
        [Nome] [nvarchar](100) NOT NULL,
        [Logo] [text] NOT NULL,
        CONSTRAINT [PK_Empresa] PRIMARY KEY CLUSTERED 
    (
	    [Id] ASC
    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END